1.2.0
peercoin/peercoin_flutter pull request #236
Opened 2023-09-07 09:59 UTC by willyfromtheblock

pipeline test

2023-09-07 14:55 UTC, MatthewLM requested changes
Looks good overall. I've made some suggestions that aren't very important, though there are a few issues of note: It looks like the `_wifs` map might be broken and the OP_RETURN handling can be improved.

2023-09-07 14:55 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
> +          final code = script[0] as ScriptOpCode;
What if it isn't a `ScriptOpCode`? Then this would error. The recommended way to test for `OP_RETURN` below would be `script[0].match(opReturn);` with `opReturn` set as `static final opReturn = ScriptOpCode.fromName("RETURN")`.

2023-09-07 14:55 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
> +        getWifFromHDPrivateKey(identifier, hdWallet);
Why are WIFs being mapped to themselves? Isn't this supposed to map addresses here?

2023-09-07 14:55 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
> +        );
Might be cleaner to construct the input and output lists first and then construct the `Transaction` object below taking the input and output lists as arguments.

2023-09-07 14:55 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
> +            ScriptOpCode.fromName('RETURN'),
Could replace with the suggested static variable: `opReturn`.

2023-09-07 14:55 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
> +            Program.match(script),
Should use a `RawProgram` directly here with no need for matching.

2023-09-07 14:55 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
The `Transaction` object could be constructed here from input and output lists.

2023-09-07 14:55 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
> +        final intermediate = tx;
Surely the alias can be removed and `tx` used instead.

2023-09-07 14:55 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
>      var hash = sha256.convert(script).toString();
Many vars that can be final instead.

2023-09-08 10:08 UTC, willyfromtheblock commented on .github/workflows/analyze-test.yml
> +    - run: dart run coinlib:build_macos
Let's try targeting web and see if that makes a difference
https://github.com/peercoin/peercoin_flutter/pull/236/commits/67a94b64593a0c9f1bdb32fad18cd8d12727d942

2023-09-08 10:08 UTC, willyfromtheblock commented on .github/workflows/analyze-test.yml
> +        run: dart run coinlib:build_macos
It actually wasn't
https://github.com/peercoin/peercoin_flutter/pull/236/commits/b71f0319e9ddf99a5ccc1d3165daf39ced79d0ae

2023-09-08 10:09 UTC, willyfromtheblock commented on lib/main.dart
> +  await loadCoinlib();
I would like to stick with this approach. This leaves the native splash screen displayed until the app is fully interactive.

2023-09-08 11:19 UTC, MatthewLM commented on .github/workflows/analyze-test.yml
> +    - run: dart run coinlib:build_macos
Looks like the web tests work OK so the build command can be removed above.

2023-09-08 12:57 UTC, MatthewLM commented on .github/workflows/analyze-test.yml
> +    - run: dart run coinlib:build_macos
Scratch that. The macOS test environment should be OK to keep. It's not taking too long and the web tests can be slower anyway making the overall difference probably small.

2023-09-12 10:28 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +  }
https://github.com/peercoin/peercoin_flutter/commit/e27bc0789144b503d56d051013dc2641158296ef

2023-09-12 10:28 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +  }
https://github.com/peercoin/peercoin_flutter/commit/e27bc0789144b503d56d051013dc2641158296ef

2023-09-12 10:30 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +        address: getAddressFromHDPrivateKey(
https://github.com/peercoin/peercoin_flutter/commit/bd109f2a2468267fe2596763a8b9df3a832881be

2023-09-12 11:57 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +          final code = script[0] as ScriptOpCode;
https://github.com/peercoin/peercoin_flutter/commit/66d5dd03362a71abe72015aaabfa57e671862abe

2023-09-12 11:57 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +              if (op is ScriptPushData) {
https://github.com/peercoin/peercoin_flutter/commit/66d5dd03362a71abe72015aaabfa57e671862abe

2023-09-12 12:03 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +        getWifFromHDPrivateKey(identifier, hdWallet);
https://github.com/peercoin/peercoin_flutter/commit/15a0cc274c41d51d147a0528b0c9e8aa913fa1b9

this should make more sense

2023-09-12 12:06 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +            ScriptPushData(Uint8List.fromList(opReturn.codeUnits)),
that would return a List<int>, not Uint8List as required for ScriptPushData

2023-09-12 12:07 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +            ScriptOpCode.fromName('RETURN'),
https://github.com/peercoin/peercoin_flutter/commit/2666d3d4ceff37307627a30ba26b19f8e2d4a205

2023-09-12 12:07 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +            Program.match(script),
https://github.com/peercoin/peercoin_flutter/commit/2666d3d4ceff37307627a30ba26b19f8e2d4a205

2023-09-12 12:14 UTC, willyfromtheblock commented on lib/screens/wallet/import_wif.dart
> +      );
https://github.com/peercoin/peercoin_flutter/commit/e3015b9600ea508b88c96141665afcccbeb4ff6e

2023-09-12 12:15 UTC, willyfromtheblock commented on lib/screens/wallet/import_paper_wallet.dart
> +      );
https://github.com/peercoin/peercoin_flutter/commit/86e1dec704c912541c292dd69f27161c2baa2a7e

2023-09-12 12:19 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
>      var hash = sha256.convert(script).toString();
https://github.com/peercoin/peercoin_flutter/commit/625056a3548074161ff0fd67d4698e4fc7c04c82

2023-09-12 12:20 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +        final intermediate = tx;
https://github.com/peercoin/peercoin_flutter/commit/a1fb257b6f279cf00ea6df7a1f66b1ed8ab8a0bf

2023-09-12 12:25 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
>          Future<Map<int, Map>> generateKeyMap() async {
https://github.com/peercoin/peercoin_flutter/commit/efa008e73397dacb031be8524f6bca8827ff42ab

2023-09-12 12:25 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
>              var inputKey = inputTx.indexOf(inputUtxo);
https://github.com/peercoin/peercoin_flutter/commit/efa008e73397dacb031be8524f6bca8827ff42ab

2023-09-12 12:32 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
https://github.com/peercoin/peercoin_flutter/commit/521a78e17c3ec1b384d790548d70feef3a242d0d

2023-09-12 13:06 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +            ScriptPushData(Uint8List.fromList(opReturn.codeUnits)),
https://github.com/peercoin/peercoin_flutter/commit/750e257c090ad37af18fd4ba0563e2730ddea7eb

2023-09-12 14:19 UTC, MatthewLM requested changes
Mostly looks good. I have a few further suggestions on code quality.

2023-09-12 14:19 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
>          }
Could maybe do something like this to return the unknown txs without need for the loops.

 ```dart
return newTxList.map(
    (tx) => tx['tx_hash']
).where(
    (txid) => storedTransactions.any((storedTx) => storedTx.txid == txid)
).toList();
```

Also the return type can be `Future<List<String>>`.

2023-09-12 14:19 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
> +      if (notify == true) {
Unnecessary `== true`.

2023-09-12 14:19 UTC, MatthewLM commented on lib/providers/wallet_provider.dart
> +          txOutputs.add(output);
The object can go directly into the `add` parameter with no need for the `output` variable.

2023-09-12 14:19 UTC, MatthewLM commented on lib/screens/wallet/import_paper_wallet.dart
> +    if (error == false) {
Can be changed to `if (!validateWIFPrivKey(privKey)) {`. That's confusing though why `validateWIFPrivKey` is returning false on validation.

2023-09-12 14:19 UTC, MatthewLM commented on lib/tools/validators.dart
> +}
Sure this should return true on success. Could be done much like `validateAddress` above.

2023-09-12 14:26 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
>          }
https://github.com/peercoin/peercoin_flutter/commit/ec6f378b9dfe8b643aa8dc10e7d05cf6fd53d5a0

2023-09-12 14:27 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +      if (notify == true) {
Old javascript habbit. There are 78 more examples of this in the codebase.

2023-09-12 14:29 UTC, willyfromtheblock commented on lib/providers/wallet_provider.dart
> +          txOutputs.add(output);
https://github.com/peercoin/peercoin_flutter/commit/f96394511c6b26020c83731d9c69f5bcbfe8ae3b

2023-09-12 14:32 UTC, willyfromtheblock commented on lib/tools/validators.dart
> +}
absolutely. 
https://github.com/peercoin/peercoin_flutter/commit/515991de28f66d90e6639f66879bcae7e5eadfcd

2023-09-12 14:33 UTC, willyfromtheblock commented on lib/screens/wallet/import_paper_wallet.dart
> +    if (error == false) {
https://github.com/peercoin/peercoin_flutter/commit/515991de28f66d90e6639f66879bcae7e5eadfcd

2023-09-12 17:01 UTC, merged